language: python
sudo: false

notifications:
  email: false

matrix:
  include:
    - JUPYTER_VERSION: "4.*"
      python: "3.5"
    - JUPYTER_VERSION: "4.*"
      python: "2.7"
    - JUPYTER_VERSION: "5.*"
      python: "3.5"
    - JUPYTER_VERSION: "5.*"
      python: "2.7"
      
before_install:
  - pwd
  - source .ci/install_go.sh
  - source .ci/install_python.sh
  - source .ci/start_minio.sh

install:
  - which python
  - pip freeze
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip freeze

script:
  - py.test -s -vv --cov=s3contents --cov-report term-missing

after_success:
  - coveralls
