language: python
sudo: false

notifications:
  email: false

python:
  - 2.7
  - 3.5

env:
  - JUPYTER_VERSION="4.*"
  - JUPYTER_VERSION="5.*"

before_install:
  - pwd
  # - source .ci/install_go.sh
  # - source .ci/install_python.sh
  - source .ci/start_minio.sh

install:
  - which python
  - pip freeze
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip freeze

script:
  - py.test -s -vv --cov=s3contents --cov-report term-missing

after_success:
  - coveralls
