language: python
sudo: false

notifications:
  email: false

python:
  - 2.7
  - 3.5

env:
  - JUPYTER_VERSION="4.*"
  - JUPYTER_VERSION="5.1"
  - JUPYTER_VERSION="5.2"
  - JUPYTER_VERSION="5.3"
  - JUPYTER_VERSION="5.4"
  - JUPYTER_VERSION="5.6"
  - JUPYTER_VERSION="5.7"
  - JUPYTER_VERSION="5.*"
  - JUPYTER_VERSION="6.*"

before_install:
  - pwd
  - source ci/start_minio.sh
  - source ci/install_python.sh

install:
  - which python
  - pip freeze
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pip freeze

script:
  - py.test -s -vv --cov=s3contents --cov-report term-missing

after_success:
  - coveralls

after_failure:
  - cat /tmp/minio.log
